# Apêndice A

The ISO-3166-1 alpha-2 country code that is associated with the target.
[Fonte](https://developers.google.com/adwords/api/docs/appendix/geotargeting): https://developers.google.com/adwords/api/docs/appendix/geotargeting

n | Critério ID | Nome | Nome Canônico | Código do País | Tipo
----- | ----- | ----- | ----- | ----- | ----- 
1 | 2004 | Afghanistan | Afghanistan | AF | Country
2 | 2008 | Albania | Albania | AL | Country
3 | 2010 | Antarctica | Antarctica | AQ | Country
4 | 2012 | Algeria | Algeria | DZ | Country
5 | 2016 | American Samoa | American Samoa | AS | Country
6 | 2020 | Andorra | Andorra | AD | Country
7 | 2024 | Angola | Angola | AO | Country
8 | 2028 | Antigua and Barbuda | Antigua and Barbuda | AG | Country
9 | 2031 | Azerbaijan | Azerbaijan | AZ | Country
10 | 2032 | Argentina | Argentina | AR | Country
11 | 2036 | Australia | Australia | AU | Country
12 | 2040 | Austria | Austria | AT | Country
13 | 2044 | The Bahamas | The Bahamas | BS | Country
14 | 2048 | Bahrain | Bahrain | BH | Country
15 | 2050 | Bangladesh | Bangladesh | BD | Country
16 | 2051 | Armenia | Armenia | AM | Country
17 | 2052 | Barbados | Barbados | BB | Country
18 | 2056 | Belgium | Belgium | BE | Country
19 | 2064 | Bhutan | Bhutan | BT | Country
20 | 2068 | Bolivia | Bolivia | BO | Country
21 | 2070 | Bosnia and Herzegovina | Bosnia and Herzegovina | BA | Country
22 | 2072 | Botswana | Botswana | BW | Country
23 | 2076 | Brazil | Brazil | BR | Country
24 | 2084 | Belize | Belize | BZ | Country
25 | 2090 | Solomon Islands | Solomon Islands | SB | Country
26 | 2096 | Brunei | Brunei | BN | Country
27 | 2100 | Bulgaria | Bulgaria|  BG | Country
28 | 2108 | Burundi | Burundi | BI | Country
29 | 2112 | Belarus | Belarus | BY | Country
30 | 2116 | Cambodia | Cambodia | KH | Country
31 | 2120 | Cameroon | Cameroon | CM | Country
32 | 2124 | Canada | Canada | CA | Country
33 | 2132 | Cape Verde | Cape Verde | CV | Country
34 | 2140 | Central African Republic | Central African Republic | CF | Country
35 | 2144 | Sri Lanka | Sri Lanka | LK | Country
36 | 2148 | Chad | Chad | TD | Country
37 | 2152 | Chile | Chile | CL | Country
38 | 2156 | China | China | CN | Country
39 | 2162 | Christmas Island | Christmas Island | CX | Country
40 | 2166 | Cocos (Keeling) Islands | Cocos (Keeling) Islands | CC | Country
41 | 2170 | Colombia | Colombia | CO | Country
42 | 2174 | Comoros | Comoros | KM | Country
43 | 2178 | Congo | Congo | CG | Country
44 | 2180 | Democratic Republic of the Congo | Democratic Republic of the Congo | CD | Country
45 | 2184 | Cook Islands | Cook Islands | CK | Country
46 | 2188 | Costa Rica | Costa Rica | CR | Country
47 | 2191 | Croatia | Croatia | HR | Country
48 | 2196 | Cyprus | Cyprus | CY | Country
49 | 2203 | Czech Republic | Czech Republic | CZ | Country
50 | 2204 | Benin | Benin | BJ | Country
51 | 2208 | Denmark | Denmark | DK | Country
52 | 2212 | Dominica | Dominica | DM | Country
53 | 2214 | Dominican Republic | Dominican Republic | DO | Country
54 | 2218 | Ecuador | Ecuador | EC | Country
55 | 2222 | El Salvador | El Salvador | SV | Country
56 | 2226 | Equatorial Guinea | Equatorial Guinea | GQ | Country
57 | 2231 | Ethiopia | Ethiopia | ET | Country
58 | 2232 | Eritrea | Eritrea | ER | Country
59 | 2233 | Estonia | Estonia | EE | Country
60 | 2239 | South Georgia and the South Sandwich Islands | South Georgia and the South Sandwich Islands | GS | Country
61 | 2242 | Fiji | Fiji | FJ | Country
62 | 2246 | Finland | Finland | FI | Country
63 | 2250 | France | France | FR | Country

PAREI NO APENDICE A